name: HavenBags
main: valorless.havenbags.Main
version: 1.21.2.1542
author: Valorless
api-version: 1.17
website: https://www.spigotmc.org/resources/110420/
description: Create shulker-like bags of varying sizes bound to a player, or accessible by anyone.
depend: [ValorlessUtils]
softdepend: [ChestSort, PlaceholderAPI, AngelChest, PvPManager]
commands:
  havenbags:
    description: Main command.
    usage:
    aliases: [bags, bag]
permissions:
  havenbags.player:
    description: Gives access to all player commands.
    children:
      havenbags.use: true
      havenbags.rename: true
      havenbags.empty: true
      havenbags.autoloot: true
      havenbags.open.9: true
      havenbags.open.18: true
      havenbags.open.27: true
      havenbags.open.36: true
      havenbags.open.45: true
      havenbags.open.54: true
      havenbags.trust: true
      havenbags.upgrade.9: true
      havenbags.upgrade.18: true
      havenbags.upgrade.27: true
      havenbags.upgrade.36: true
      havenbags.upgrade.45: true
  havenbags.admin:
    description: Gives access to all admin commands.
    children:
      havenbags.reload: true
      havenbags.create: true
      havenbags.give: true
      havenbags.restore: true
      havenbags.bypass: true
      havenbags.preview: true
      havenbags.info: true
      havenbags.gui: true
      havenbags.weight: true
      havenbags.help: true
      havenbags.texture: true
      havenbags.token: true
  havenbags.reload:
    description: Allows you to reload the configuration.
    default: op
  havenbags.use:
    description: Allows you to use bags.
    default: op
#  havenbags.open:
#    description: Allows you to remotely open bags.
#    default: op
  havenbags.rename:
    description: Allows you to rename bags. Without havenbags.bypass, you can only rename your own bags.
    default: op
  havenbags.create:
    description: Allows you to create bags.
    default: op
  havenbags.give:
    description: Allows you to give bags.
    default: op
  havenbags.restore:
    description: Allows you to restore bags.
    default: op
  havenbags.bypass:
    description: Allows you to bypass ownership locks.
    default: op
  havenbags.preview:
    description: Allows you to bypass preview bags.
    default: op
  havenbags.info:
    description: Allows you to view information regarding the currently held-in-hand bag.
    default: op
  havenbags.gui:
    description: Allows you to open the Admin GUI.
    default: op
  havenbags.empty:
    description: Allows you to empty bags onto the ground.
    default: op
  havenbags.help:
    description: Allows you to use '/havenbags help'.
    default: op
  havenbags.autopickup:
    description: Allows you to use the auto-pickup feature.
    default: op
  havenbags.weight:
    description: Allows you to set the weight limit of bags.
    default: op
  havenbags.open.9:
    description: Allows you to open bags with a size of 9.
    default: op
  havenbags.open.18:
    description: Allows you to open bags with a size of 18.
    default: op
  havenbags.open.27:
    description: Allows you to open bags with a size of 27.
    default: op
  havenbags.open.36:
    description: Allows you to open bags with a size of 36.
    default: op
  havenbags.open.45:
    description: Allows you to open bags with a size of 45.
    default: op
  havenbags.open.54:
    description: Allows you to open bags with a size of 54.
    default: op
  havenbags.trust:
    description: Allows you to trust other players to open your bag.
    default: op
  havenbags.texture:
    description: Allows you to set textures of bags you own.
    default: op
  havenbags.upgrade.9:
    description: Allows you to upgrade bags with a size of 9.
    default: op
  havenbags.upgrade.18:
    description: Allows you to upgrade bags with a size of 18.
    default: op
  havenbags.upgrade.27:
    description: Allows you to upgrade bags with a size of 27.
    default: op
  havenbags.upgrade.36:
    description: Allows you to upgrade bags with a size of 36.
    default: op
  havenbags.upgrade.45:
    description: Allows you to upgrade bags with a size of 45.
    default: op
  havenbags.token:
    description: Allows you create skin tokens.
    default: op
  