name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4

    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Get the short Git commit hash
    - name: Get Git Commit Hash
      id: commit_hash
      run: echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Get Git Branch Name
      id: branch_name
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Verify Commit Hash & Branch
      run: |
        echo "Commit hash is: $commit"
        echo "Branch is: $branch"

    # Step 1: Download BuildTools
    - name: Download BuildTools
      run: |
        curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        
    # Step 2: Run BuildTools to generate Spigot
    - name: Generate Spigot
      run: |
        java -jar BuildTools.jar --rev 1.21.1
        
    # Step 3: Verify that Spigot is installed
    - name: Verify Spigot Installation
      run: |
        ls ~/.m2/repository/org/spigotmc/spigot/1.21.1-R0.1-SNAPSHOT

    # Extract version from main pom.xml
    - name: Get version from main pom.xml
      id: get_version
      run: |
        VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    # Replace <version>0.0.0</version> in github/pom.xml
    - name: Update version in pom.github.xml
      run: |
        sed -i "s/<version>0.0.0<\/version>/<version>${{ env.VERSION }}<\/version>/g" pom.github.xml

    # Clean with Maven using the custom pom.xml in github folder
    - name: Clean with Maven
      run: mvn clean -f pom.github.xml

    # Build with Maven using the custom pom.xml in github folder
    - name: Build with Maven
      run: mvn install -f pom.github.xml

    # Rename the built JAR with the commit hash
    - name: Rename Built JAR
      run: |
        mv target/HavenBags.jar target/HavenBags-$branch-$commit.jar

    # Verify the renamed file
    - name: Verify Renamed JAR
      run: ls target/
      
    # Step: Download Paper/Spigot jar (faster than running BuildTools again)
    - name: Download Paper
      run: |
        curl -o server.jar https://api.papermc.io/v2/projects/paper/versions/1.21.1/builds/122/downloads/paper-1.21.1-122.jar

    # Step: Accept EULA
    - name: Accept EULA
      run: echo "eula=true" > eula.txt
      
    # Step: Download ValorlessUtils dependency
    - name: Download ValorlessUtils
      run: |
        mkdir -p plugins
        curl -s https://api.github.com/repos/valorless/ValorlessUtils/releases/latest \
        | grep "browser_download_url.*\.jar" \
        | cut -d '"' -f 4 \
        | wget -qi - -O plugins/ValorlessUtils.jar

    # Step: Place our plugin into plugins folder
    - name: Setup plugin
      run: |
        cp target/HavenBags-${{ env.branch }}-${{ env.commit }}.jar plugins/

    # Step: Run the server headless to check plugin enable/disable
    - name: Run server test
      run: |
        # Start server and tee output to both console and log file
        java -Xmx1G -jar server.jar --nogui 2>&1 | tee server.log &
        PID=$!

        # Give it some time to boot and load plugins (max 60s)
        sleep 60

        echo "=== Stopping server ==="
        # Try graceful stop
        kill $PID || true

        # Wait up to 10s for shutdown
        for i in {1..10}; do
          if ! kill -0 $PID 2>/dev/null; then
            break
          fi
          sleep 1
        done

        # Force kill if still running
        if kill -0 $PID 2>/dev/null; then
          echo "⚠️ Server did not stop gracefully, killing..."
          kill -9 $PID
        fi

        wait $PID || true

        echo "=== Checking server.log for errors ==="
        tail -n 100 server.log

        if grep -q "\[SEVERE\]" server.log || grep -q "Exception" server.log; then
          echo "❌ Errors found in server log!"
          exit 1
        else
          echo "✅ No severe errors found."
        fiho "✅ No severe errors found."
        fi
    
    # Upload the JAR as an artifact
    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HavenBags-${{ env.branch }}-${{ env.commit }}.jar
        path: target/HavenBags-${{ env.branch }}-${{ env.commit }}.jar  # Use env.commit and env.branch for proper variable interpolation
